'use strict';

export const GH = [
  {
    name: 'Ahmed Gaber',
    // cohort: null,
    email: null,
    github: 'https://github.com/LimitToInfinity',
    linkedin: 'https://www.linkedin.com/in/ahmedtgaber/',
    medium: 'https://medium.com/@21stlimitless',
    website: null,
  },
  {
    name: 'Alexander Gabriel',
    // cohort: 'Illicit Syntax',
    email: 'alexandrgabe@gmail.com',
    github: 'https://github.com/kosmos02',
    linkedin: 'https://www.linkedin.com/in/alexander-m-gabriel/',
    medium: 'https://alexandermgabriel.medium.com/',
    website: null,
  },
  {
    name: 'Luis Garcia',
    // cohort: 'Git Forked',
    email: 'garciale308@gmail.com',
    github: 'https://github.com/luies24',
    linkedin: 'https://www.linkedin.com/in/garciale308/',
    medium: null,
    website: null,
  },
  {
    name: 'Miwha Geschwind',
    // cohort: 'Die Prying',
    email: 'miwha.geschwind@gmail.com',
    github: 'https://github.com/miwhag',
    linkedin: 'https://www.linkedin.com/in/miwha-geschwind/',
    medium: 'https://medium.com/@miwhag',
    website: 'https://miwha.co/',
  },
  {
    name: 'James Giosmas',
    // cohort: 'Notorious Git',
    email: 'giosmasj@gmail.com',
    github: 'https://github.com/giosmasj',
    linkedin: 'https://www.linkedin.com/in/james-giosmas/',
    medium: null,
    website: null,
  },
  {
    name: 'Kevin Glasgow',
    // cohort: 'Illicit Syntax',
    email: 'kglas001@gmail.com',
    github: 'https://github.com/TheRealKevBot',
    linkedin: 'https://www.linkedin.com/in/kevin-glasgow/',
    medium: 'https://real-kevbot.medium.com/',
    website: null,
  },
  {
    name: 'Sam Gold',
    // cohort: 'Hip Hip Arrays',
    email: 'samgolddev@gmail.com',
    github: 'https://github.com/sgold57',
    linkedin: 'https://www.linkedin.com/in/samgold57/',
    medium: null,
    website: 'https://samgolddev.tech/',
  },
  {
    name: 'Sydney Goldberg',
    // cohort: 'Only Spans',
    email: null,
    github: null,
    linkedin: null,
    medium: null,
    website: null,
  },
  {
    name: 'Jeff Golden',
    // blogger: 'http://gjeffgolden.blogspot.com/',
    // cohort: 'Hip Hip Arrays',
    email: 'codebygolden@gmail.com',
    // email: 'gjgolden08@gmail.com',
    github: 'https://github.com/gjeffgolden',
    linkedin: 'https://www.linkedin.com/in/gjeffgolden/',
    medium: null,
    // twitter: 'https://twitter.com/GJeffGolden',
    website: 'https://gjeffgolden.com/',
  },
  {
    name: 'Brian Gordon',
    // cohort: 'Illicit Syntax',
    email: null,
    github: null,
    linkedin: null,
    medium: null,
    website: null,
  },
  {
    name: 'Jeremy Gray',
    // cohort: 'Die Prying',
    email: 'jeremytgray6@gmail.com',
    github: 'https://github.com/jtgray6',
    linkedin: 'https://www.linkedin.com/in/jeremytgray6/',
    medium: null,
    website: null,
  },
  {
    name: 'Nick Gray',
    // cohort: 'Juicy Functions',
    email: 'nickgray87@gmail.com',
    github: 'https://github.com/nickgray06',
    linkedin: 'https://www.linkedin.com/in/nick-gray-06/',
    medium: null,
    website: null,
  },
  {
    name: 'Evan Greer',
    // cohort: 'Die Prying',
    email: 'etgreer91@gmail.com',
    github: 'https://github.com/evantk91',
    linkedin: 'https://www.linkedin.com/in/evantk91/',
    medium: 'https://etgreer91.medium.com/',
    website: 'https://www.evan-greer.co/',
  },
  {
    name: 'Lydia Gregory',
    // cohort: 'Notorious Git',
    email: 'lydia.gregory.dev@gmail.com',
    github: 'https://github.com/ljg2gb',
    linkedin: 'https://www.linkedin.com/in/lydia-gregory/',
    medium: null,
    website: 'https://lydiagregory.dev/',
  },
  {
    name: 'Jennifer Grenier',
    // cohort: 'Git Forked',
    email: 'jenniferagrenier@gmail.com',
    github: 'https://github.com/JAGrenier',
    linkedin: 'https://www.linkedin.com/in/jagrenier/',
    medium: 'https://jagrenier.medium.com/',
    website: null,
  },
  {
    name: 'Nathan Gusky',
    // cohort: 'Juicy Functions',
    email: 'nathangusky13@gmail.com',
    github: 'https://github.com/Guskyn13',
    linkedin: 'https://www.linkedin.com/in/nathankgusky/',
    medium: null,
    website: null,
  },
  {
    name: 'Phil Haines',
    // cohort: 'Juicy Functions',
    email: 'phil.haines92@gmail.com',
    github: 'https://github.com/philip-haines',
    linkedin: 'https://www.linkedin.com/in/philip-haines/',
    medium: null,
    website: 'https://www.philiphaines.com/',
  },
  {
    name: 'Bradley Haley',
    // cohort: 'Die Prying',
    email: 'Bshaley25@gmail.com',
    github: 'https://github.com/bshaley25',
    linkedin: 'https://www.linkedin.com/in/bradley-haley-44a85b19a/',
    medium: null,
    website: null,
  },
  {
    name: 'Tara Harwood',
    // cohort: 'Juicy Functions',
    email: 'tara.m.harwood@gmail.com',
    github: 'https://github.com/tara-m-harwood',
    linkedin: 'https://www.linkedin.com/in/taraharwood/',
    medium: null,
    website: null,
  },
  {
    name: 'Chris Henderson',
    // cohort: 'Illicit Syntax',
    email: null,
    github: null,
    linkedin: null,
    medium: null,
    website: null,
  },
  {
    name: 'David Henderson',
    // cohort: 'Hackstreet {Boiz}',
    email: 'me@davidhenderson.tech',
    github: 'https://github.com/notDavidHenderson',
    linkedin: 'https://www.linkedin.com/in/davidhendersontech/',
    medium: null,
    website: null,
  },
  {
    name: 'Grant Hesketh',
    // cohort: 'Hip Hip Arrays',
    email: 'ghesketh76@gmail.com',
    github: 'https://github.com/ghesketh76',
    linkedin: 'https://www.linkedin.com/in/granthesketh/',
    medium: 'https://ghesketh76.medium.com/',
    website: null,
  },
  {
    name: 'John Higger',
    // cohort: null,
    email: null,
    github: 'https://github.com/jjhiggz',
    linkedin: 'https://www.linkedin.com/in/jonathan-higger/',
    medium: 'https://medium.com/@jonathan.higger',
    website: null,
  },
  {
    name: 'Corey Hodge',
    // cohort: 'Die Prying',
    email: 'contact@coreyhodge.net',
    github: 'https://github.com/WordsPerMinute',
    linkedin: 'https://www.linkedin.com/in/coreyhodge/',
    medium: 'https://medium.com/@coreyhodgedotnet',
    website: 'https://coreyhodge.net/',
  },
  {
    name: 'Jesse Houser',
    // cohort: 'Hackstreet {Boiz}',
    email: 'jesseahouser@gmail.com',
    github: 'https://github.com/jesseahouser',
    linkedin: 'https://www.linkedin.com/in/jesseahouser/',
    medium: null,
    website: null,
  },
  {
    name: 'Jack Hubert',
    // cohort: 'Hip Hip Arrays',
    email: 'jphubert93@gmail.com',
    github: 'https://github.com/hydroflux',
    linkedin: 'https://www.linkedin.com/in/jackhubert/',
    medium: null,
    website: null,
  },
  {
    name: 'Greg Hughes',
    // cohort: 'Team 404',
    email: 'ghughes610@gmail.com',
    github: 'https://github.com/catman237',
    linkedin: 'https://www.linkedin.com/in/greg-hughes-ba2aa497/',
    medium: null,
    website: null,
  },
];
