'use strict';

const main = document.querySelector('main');

const users = [
  {
    name: 'Raz Al-Jaf',
    website: null,
    github: 'https://github.com/ThatoneKurdishSE',
    linkedin: 'https://www.linkedin.com/in/razaljaf/',
    medium: 'https://razaljaf.medium.com/',
    email: 'razaljaf@gmail.com',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Ryan Anderson',
    website: null,
    github: null,
    linkedin: null,
    medium: null,
    email: 'ryan.t.anderson19@gmail.com',
    // cohort: 'Notorious Git 7/9/20',
  },
  {
    name: 'Thomas Bachorz',
    // website: 'https://tjbachorz.live/',
    website: 'tjbachorz.live',
    linkedin: 'https://www.linkedin.com/in/tjbachorz/',
    github: 'https://github.com/TJBachorz',
    medium: 'https://tjbachorz.medium.com/',
    // twitter: 'https://twitter.com/ThomasBachorz',
    email: null,
    // cohort: '',
  },
  {
    name: 'Nyaradzo Bere',
    website: null,
    linkedin: 'https://www.linkedin.com/in/nyaradzo-bere/',
    github: 'https://github.com/NyaradzoUBere',
    medium: 'https://medium.com/@nyaradzobere',
    email: 'nybe5598@colorado.edu',
    // cohort: 'Run Time Terrors',
  },
  {
    name: 'Gerald Bivens',
    // website: 'https://jamespeirce.com/',
    website: 'jamespeirce.com',
    linkedin: 'https://www.linkedin.com/in/gerald-bivens/',
    github: 'https://github.com/geraldbivens',
    medium: 'https://medium.com/@geraldbivens',
    email: 'geraldbivens@gmail.com',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Javaria Brascom',
    website: null,
    linkedin: 'https://www.linkedin.com/in/javaria-brascom-0510991bb/',
    github: 'https://github.com/jay719',
    medium: 'https://javariab17.medium.com/',
    email: 'javariab17@gmail.com',
    // cohort: 'Illicit Syntax',
  },
  {
    name: 'Bradley Calkins',
    website: null,
    linkedin: 'https://www.linkedin.com/in/bradley-calkins/',
    github: 'https://github.com/bmcalkins',
    medium: 'https://bradleycalkins.medium.com/',
    email: 'b.raders1013@gmail.com',
    // cohort: '',
  },
  {
    name: 'Damon Chivers',
    // website: 'https://www.damonchivers.com/',
    website: 'damonchivers.com',
    linkedin: 'https://www.linkedin.com/in/damon-chivers/',
    github: 'https://github.com/DamonLC21',
    medium: null,
    email: null,
  },
  {
    name: 'Ryan Choe',
    // website: 'https://ryanachoe.com/',
    website: 'ryanachoe.com',
    linkedin: 'https://www.linkedin.com/in/ryanchoe1229/',
    github: 'https://github.com/rchoe1229',
    medium: 'https://chowderchoe.medium.com/',
    email: 'Ryan.Choe@outlook.com',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Katie Clark',
    // website: 'https://www.katielaelclark.me/',
    website: 'katielaelclark.me',
    linkedin: 'https://www.linkedin.com/in/kathryn-clark-fullstackprogrammer/',
    github: 'https://github.com/kathryn0908/',
    medium: null,
    email: 'kathrynlael@gmail.com',
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Kyle Coberly',
    // website: 'https://kylecoberly.com/',
    website: 'kylecoberly.com',
    linkedin: 'https://www.linkedin.com/in/kylecoberly/',
    github: 'https://github.com/kylecoberly',
    medium: 'https://medium.com/@kyle.coberly',
    email: 'kyle.coberly@gmail.com',
  },
  // {
  //   name: 'Cristina Cristobal',
  //   website: null,
  //   linkedin: null,
  //   github: null,
  //   medium: 'https://medium.com/@cristicristo',
  //   email: null,
  // },
  {
    name: 'Mike De La Rosa',
    website: null,
    linkedin: 'https://www.linkedin.com/in/mdelarosa/',
    github: 'https://github.com/mdelarosa',
    medium: null,
    email: 'mdelarosa86@gmail.com',
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Hannah Drury',
    website: null,
    linkedin: 'https://www.linkedin.com/in/hannah-drury/',
    github: 'https://github.com/wolf-dominion',
    medium: null,
    email: 'hannahdruryutd@gmail.com',
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Kristine Du',
    website: null,
    linkedin: 'https://www.linkedin.com/in/kristine-du/',
    github: 'https://github.com/kadrianne',
    medium: 'https://kristine-a-du.medium.com/',
    email: 'kristine.a.du@gmail.com',
    // cohort: '',
  },
  {
    name: 'Nolan Dyke',
    website: null,
    linkedin: 'https://www.linkedin.com/in/nolan-dyke/',
    github: null,
    medium: null,
    email: 'nolan.g.dyke@gmail.com',
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Ben Dunn',
    website: null,
    linkedin: 'https://www.linkedin.com/in/ben-dunn-15977b15b/',
    github: 'https://github.com/btdunn',
    medium: 'https://benthedunn.medium.com/',
    email: 'benthedunn@gmail.com',
    // cohort: 'Run Time Terrors',
  },
  {
    name: 'Nathan Fedzen',
    website: null,
    linkedin: 'https://www.linkedin.com/in/nathan-fedzen/',
    github: 'https://github.com/nfedzen',
    medium: null,
    email: 'nathanfedzen@gmail.com',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'David Fertitta',
    website: null,
    linkedin: 'https://www.linkedin.com/in/david-fertitta-99298715b/',
    github: null,
    medium: null,
    email: 'davidj.fertitta@gmail.com',
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Brian Firooz',
    website: null,
    linkedin: 'https://www.linkedin.com/in/brian-firooz/',
    github: null,
    medium: null,
    email: 'brianfirooz@mac.com',
    // twitter: 'https://twitter.com/brianfirooz',
  },
  {
    name: 'Ahmed Gaber',
    website: null,
    linkedin: 'https://www.linkedin.com/in/ahmedtgaber/',
    github: 'https://github.com/LimitToInfinity',
    medium: 'https://medium.com/@21stlimitless',
    email: null,
    // cohort: '',
  },
  {
    name: 'Alexander Gabriel',
    website: null,
    linkedin: 'https://www.linkedin.com/in/alexander-m-gabriel/',
    github: 'https://github.com/kosmos02',
    medium: 'https://alexandermgabriel.medium.com/',
    email: 'alexandrgabe@gmail.com',
    // cohort: 'Illicit Syntax',
  },
  {
    name: 'James Giosmas',
    website: null,
    linkedin: 'https://www.linkedin.com/in/james-giosmas/',
    github: 'https://github.com/giosmasj',
    medium: null,
    email: 'giosmasj@gmail.com',
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Kevin Glasgow',
    website: null,
    linkedin: 'https://www.linkedin.com/in/kevin-glasgow/',
    github: 'https://github.com/TheRealKevBot',
    medium: 'https://real-kevbot.medium.com/',
    email: 'kglas001@gmail.com',
    // cohort: 'Illicit Syntax',
  },
  {
    name: 'Sam Gold',
    website: null,
    linkedin: 'https://www.linkedin.com/in/samgold57/',
    github: 'https://github.com/sgold57',
    medium: null,
    email: 'samgolddev@gmail.com',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Jeff Golden',
    // website: 'https://gjeffgolden.com/',
    website: 'gjeffgolden.com',
    linkedin: 'https://www.linkedin.com/in/gjeffgolden/',
    github: 'https://github.com/gjeffgolden',
    medium: null,
    email: 'codebygolden@gmail.com',
    // http://gjeffgolden.blogspot.com/
    // https://twitter.com/GJeffGolden
    // gjgolden08@gmail.com
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Lydia Gregory',
    // website: 'https://lydiagregory.dev/',
    website: 'lydiagregory.dev',
    linkedin: 'https://www.linkedin.com/in/lydia-gregory/',
    github: 'https://github.com/ljg2gb',
    medium: null,
    email: 'lydia.gregory.dev@gmail.com',
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Jennifer Grenier',
    website: null,
    linkedin: 'https://www.linkedin.com/in/jagrenier/',
    github: 'https://github.com/JAGrenier',
    medium: 'https://jagrenier.medium.com/',
    email: 'jenniferagrenier@gmail.com',
    // cohort: '',
  },
  {
    name: 'Grant Hesketh',
    website: null,
    linkedin: 'https://www.linkedin.com/in/granthesketh/',
    github: 'https://github.com/ghesketh76',
    medium: 'https://ghesketh76.medium.com/',
    email: 'ghesketh76@gmail.com',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'John Higger',
    website: null,
    linkedin: 'https://www.linkedin.com/in/jonathan-higger/',
    github: 'https://github.com/jjhiggz',
    medium: 'https://medium.com/@jonathan.higger',
    email: null,
    // cohort: '',
  },
  {
    name: 'Jack Hubert',
    website: null,
    linkedin: 'https://www.linkedin.com/in/jackhubert/',
    github: 'https://github.com/hydroflux',
    medium: null,
    email: 'jphubert93@gmail.com',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Zachary Jacobs',
    website: null,
    linkedin: 'https://www.linkedin.com/in/zachary-jacobs-10b3351b5/',
    github: 'https://github.com/zprogrammer-code',
    medium: null,
    email: 'zprogrammer@icloud.com',
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Lisa Jung',
    website: null,
    linkedin: 'https://www.linkedin.com/in/lisahjung/',
    github: null,
    medium: null,
    email: 'lisahjung@gmail.com',
    // dev: 'https://dev.to/lisahjung',
    // twitter: 'https://twitter.com/LisaHJung',
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Tiffany Kanjanabout',
    website: null,
    linkedin: 'https://www.linkedin.com/in/tiffany-kanjanabout/',
    github: 'https://github.com/tiffanynk',
    medium: 'https://tiffany-nit-k.medium.com/',
    email: null,
    // cohort: '',
  },
  {
    name: 'Tony Kim',
    // website: 'https://hjkmines.github.io/my-portfolio-website/',
    website: 'hjkmines.github.io/my-portfolio-website',
    linkedin: 'https://www.linkedin.com/in/hyung-kim/',
    github: 'https://github.com/hjkmines',
    medium: 'https://medium.com/@hjkmines',
    email: 'hjkmines@gmail.com',
    // cohort: 'Run Time Terrors',
  },
  {
    name: 'Austin Kohler',
    website: null,
    linkedin: null,
    github: null,
    medium: null,
    email: 'austinckohler@gmail.com',
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Allen Lea',
    website: null,
    linkedin: 'https://www.linkedin.com/in/allen-r-lea/',
    github: 'https://github.com/Allen70',
    medium: null,
    email: 'allenlea2007@gmail.com',
    // cohort: 'Illicit Syntax',
  },
  {
    name: 'Kat Leight',
    website: null,
    linkedin: 'https://www.linkedin.com/in/kat-leight/',
    github: 'https://github.com/leightkt',
    medium: 'https://kat-leight.medium.com/',
    email: 'leightkt@gmail.com',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Matt Long',
    // website: 'https://matt-long.dev/',
    website: 'matt-long.dev',
    linkedin: 'https://www.linkedin.com/in/mattlong34/',
    github: null,
    medium: 'https://mattlong34.medium.com/',
    email: 'mdlong34@gmail.com',
    // cohort: 'Run Time Terrors',
  },
  {
    name: 'JT Lu',
    // website: 'https://jtlu.dev/',
    website: 'jtlu.dev',
    linkedin: 'https://www.linkedin.com/in/jt-lu-68917394/',
    github: 'https://github.com/alohajt',
    medium: 'https://medium.com/@alohajt94',
    email: 'alohajt94@gmail.com',
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Denise Magner',
    website: null,
    linkedin: 'https://www.linkedin.com/in/denise-magner/',
    github: 'https://github.com/deerenae',
    medium: null,
    email: 'deerenae@gmail.com',
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Michael Navoy',
    website: null,
    linkedin: 'https://www.linkedin.com/in/michael-navoy/',
    github: 'https://github.com/mnavoy4',
    medium: 'https://medium.com/@mnavoy4',
    email: 'mnavoy4@gmail.com',
    // cohort: 'Run Tie Terrors',
  },
  {
    name: 'William Neal',
    website: null,
    linkedin: 'https://www.linkedin.com/in/william-neal1283/',
    github: 'https://github.com/Jawnny5',
    medium: 'https://wln-develops.medium.com/',
    email: 'wln.develops@gmail.com',
    // william.neal83@gmail.com
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Brett Needham',
    website: null,
    linkedin: 'https://www.linkedin.com/in/brettneedham88/',
    github: 'https://github.com/brettneedham88',
    medium: 'https://brettneedham88.medium.com/',
    email: 'brettneedham88@gmail.com',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Adam Nowland',
    // website: 'https://www.adam-nowland.com/',
    website: 'adam-nowland.com',
    linkedin: 'https://www.linkedin.com/in/adam-nowland/',
    github: 'https://github.com/acnowland',
    medium: null,
    email: 'acnowland@gmail.com',
    // cohort: '',
  },
  {
    name: 'Obinna Nwabia',
    website: null,
    linkedin: 'https://www.linkedin.com/in/obinna-nwabia-3245b268/',
    github: 'https://github.com/coremand',
    medium: null,
    email: 'valinevite@gmail.com',
    // cohort: 'Hip Hip Arrays',
  },
  {
    name: "Colton O'Connor",
    // website: 'https://coltonoconnor.com/',
    website: 'coltonoconnor.com',
    linkedin: 'https://www.linkedin.com/in/colton-o-connor/',
    github: 'https://github.com/bigdumbbaby',
    medium: 'https://colton-shawn-oconnor.medium.com/',
    email: 'colton.shawn.oconnor@gmail.com',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Bryan Oyloe',
    // website: 'https://bryanoyloe.com/',
    website: 'bryanoyloe.com',
    linkedin: 'https://www.linkedin.com/in/bryan-oyloe/',
    github: 'https://github.com/boyloe',
    medium: 'https://medium.com/@bryanoyloe',
    email: 'boyloe@gmail.com',
    // cohort: '',
  },
  {
    name: 'Kyle Peterson',
    // website: 'https://kylepetersen.dev/',
    website: 'kylepetersen.dev',
    linkedin: 'https://www.linkedin.com/in/kyle-petersen-27259b18b/',
    github: 'https://github.com/kpete2017',
    medium: null,
    email: 'kpete2017@gmail.com',
    // cohort: '',
  },
  {
    name: 'Jessica Pope',
    website: null,
    linkedin: 'https://www.linkedin.com/in/jessica-pope-77903033/',
    github: 'https://github.com/JdPope',
    medium: null,
    email: 'jessica.pope.co@gmail.com',
    // cohort: '',
  },
  {
    name: 'Alison Quaglia',
    website: null,
    linkedin: 'https://www.linkedin.com/in/alison-quaglia/',
    github: 'https://github.com/hylobates-lar',
    medium: 'https://medium.com/@alison.quaglia',
    email: null,
    // codepen: 'https://codepen.io/hylobates-lar',
    // cohort: '',
  },
  {
    name: 'Hailey Ringier',
    website: null,
    linkedin: 'https://www.linkedin.com/in/hailey-ringier/',
    github: 'https://github.com/haileyringier',
    medium: 'https://medium.com/@haileyringier',
    email: 'haileyringier@outlook.com',
    // youtube: 'https://www.youtube.com/channel/UCv8YpacxVgL9ShVduwb3Blg',
    // cohort: 'Run Time Terrors',
  },
  // {
  //   name: 'Summer Rizzo',
  //   website: null,
  //   dev: 'https://dev.to/rizz0s',
  //   linkedin: null,
  //   github: null,
  //   medium: null,
  //   email: null,
  // },
  {
    name: 'Arielle Ross',
    // website: 'https://arielleross.com/',
    website: 'arielleross.com',
    linkedin: 'https://www.linkedin.com/in/arielleross/',
    github: 'https://github.com/rel-ross',
    medium: 'https://arielle-10415.medium.com/',
    email: 'arielle@arielleross.com',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Iuliia Saprykina',
    // website: 'https://portfolio-saprykina.firebaseapp.com/',
    website: 'portfolio-saprykina.firebaseapp.com',
    linkedin: 'https://www.linkedin.com/in/iuliia-saprykina-ab3351100/',
    github: 'https://github.com/IuliiaSaprykina',
    medium: 'https://iuliia-proskurnina.medium.com/',
    email: 'iuliia.proskurnina@gmail.com',
    // cohort: '',
  },
  {
    name: 'Daniel Steed',
    // website: 'https://danielsteed.com/',
    website: 'danielsteed.com',
    linkedin: 'https://www.linkedin.com/in/daniel-steed/',
    github: 'https://github.com/dsteed112',
    medium: 'https://medium.com/@dsteed112',
    email: 'dsteed112@gmail.com',
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Jared Stromberg',
    website: null,
    linkedin: 'https://www.linkedin.com/in/jared-s-122690143/',
    github: 'https://github.com/jstrombe19',
    medium: 'https://medium.com/@jaredstromberg',
    email: null,
    // cohort: '',
  },
  {
    name: 'Lucas Thinnes',
    // website: 'https://lucasthinnes.com/',
    website: 'lucasthinnes.com',
    linkedin: 'https://www.linkedin.com/in/lucas-thinnes/',
    github: 'https://github.com/lukethinnes',
    medium: 'https://lucasthinnes.medium.com/',
    email: 'lukethinnes@protonmail.com',
    // cohort: 'Hip Hip Arrays 4/21/21',
  },
  {
    name: 'Colter Ulrich',
    website: null,
    linkedin: 'https://www.linkedin.com/in/colter-ulrich/',
    github: 'https://github.com/cju5025',
    medium: 'https://cju5025.medium.com/',
    email: 'cju5025@gmail.com',
    // instagram: 'https://www.instagram.com/colterulrich/',
    // soundcloud: 'https://soundcloud.com/colter-ulrich',
    // cohort: 'Illicit Syntax',
  },
  {
    name: 'Ashley Winters',
    website: null,
    linkedin: 'https://www.linkedin.com/in/ashley-winters/',
    github: 'https://github.com/ashbwinters',
    medium: null,
    email: 'ashbwinters@gmail.com',
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Blake Woodruff',
    website: null,
    linkedin: 'https://www.linkedin.com/in/blakewoodruffengineer/',
    github: 'https://github.com/Bwoodruff4',
    medium: null,
    email: 'blakewoodruff4@gmail.com',
    // cohort: 'Notorious Git 6/9/20',
  },
  {
    name: 'Angelo Xenakis',
    // website: 'http://www.angeloxenakis.com/',
    website: 'angeloxenakis.com',
    linkedin: 'https://www.linkedin.com/in/angeloxenakis/',
    github: 'https://github.com/angeloxenakis/',
    medium: 'https://medium.com/@angeloxenakis',
    email: 'evangelosalexander@gmail.com',
    // dribble: 'https://dribbble.com/AngeloTheThird',
  },
];

users.forEach(person => {
  const contactCard = document.createElement('div');
  contactCard.classList.add('contact-card');

  const name = document.createElement('h3');
  name.textContent = person.name;

  const website = document.createElement('p');
  website.classList.add('website');
  if (person.website === null) website.classList.add('hide');
  website.innerHTML = `<a href="https://${person.website}/" target="_blank" rel="noreferrer noopener">${person.website}</a>`;

  const contactInfoList = document.createElement('ul');
  contactInfoList.classList.add('contact-info-list');

  const linkedin = document.createElement('li');
  if (person.linkedin === null) linkedin.classList.add('hide');
  linkedin.innerHTML = `<a href="${person.linkedin}" target="_blank" rel="noreferrer noopener">
            <img src="/images/graphics/linkedin.png" width="20" height="20" title="LinkedIn" />
          </a>`;

  const github = document.createElement('li');
  if (person.github === null) github.classList.add('hide');
  github.innerHTML = `<a href="${person.github}" target="_blank" rel="noreferrer noopener">
            <img src="/images/graphics/github.png" width="20" height="20" title="GitHub" />
          </a>`;

  const medium = document.createElement('li');
  if (person.medium === null) medium.classList.add('hide');
  medium.innerHTML = `<a href="${person.medium}" target="_blank" rel="noreferrer noopener">
            <img src="/images/graphics/medium.png" width="20" height="20" title="Medium" />
          </a>`;

  const email = document.createElement('li');
  if (person.email === null) email.classList.add('hide');
  email.innerHTML = `<a href="mailto: ${person.email}">
          <img src="/images/graphics/email.png" width="20" height="20" title="Email" />
        </a>`;

  contactInfoList.append(linkedin, github, medium, email);

  contactCard.append(name, website, contactInfoList);

  main.append(contactCard);
});
